#!/usr/bin/env python3
"""Generate NOTICE from the per-artifact provenance manifests.

The repository root is MIT, but bundled data is not: every table carries
attribution obligations, and several are redistributed under terms their
upstream does not itself use. Describing a distribution that contains them as
simply "MIT" is wrong, so the bill of materials is generated from the manifests
rather than maintained by hand.

    python scripts/generate_notice.py            # rewrite NOTICE
    python scripts/generate_notice.py --check    # fail if NOTICE is stale
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NOTICE = ROOT / "NOTICE"

HEADER = """\
merkmal - NOTICE
================

Generated by scripts/generate_notice.py from the provenance manifests. Do not
edit by hand.

The merkmal *source code* is MIT licensed (see LICENSE). The *data artifacts*
bundled with it are not all MIT, and some carry terms that are materially
narrower. A distribution that includes these files cannot be described as
MIT-only.

This file records what is known. Entries marked UNVERIFIED were not recorded
when the artifact was produced; they must be established before the next data
release, not guessed from filenames.

This is a record, not legal advice. Verify license compatibility for your own
distribution.
"""


def load_manifests() -> list[tuple[Path, dict]]:
    out = []
    for path in sorted(ROOT.glob("models/*/provenance.json")):
        out.append((path, json.loads(path.read_text(encoding="utf-8"))))
    return out


def render() -> str:
    manifests = load_manifests()
    lines = [HEADER, "", "Summary of bundled data licenses", "-" * 32, ""]

    by_license: dict[str, list[str]] = {}
    for _, manifest in manifests:
        by_license.setdefault(manifest["license_spdx"], []).append(manifest["artifact_id"])
    for spdx in sorted(by_license):
        lines.append(f"  {spdx:<18} {', '.join(sorted(by_license[spdx]))}")
    lines.append("")

    restrictive = [s for s in by_license if s != "MIT"]
    if restrictive:
        lines += [
            "Redistribution consequences",
            "-" * 27,
            "",
            "  Some bundled tables are not MIT. In particular:",
            "",
        ]
        for spdx in sorted(restrictive):
            lines.append(f"  * {spdx}: {', '.join(sorted(by_license[spdx]))}")
        lines.append("")
        if "CC-BY-4.0" in by_license:
            lines += [
                "  CC-BY-4.0 requires attribution: credit the upstream project and",
                "  say that changes were made. Cite what each artifact's manifest",
                "  names, not this project alone.",
                "",
            ]
        if "CC-BY-SA-3.0" in by_license:
            lines += [
                "  CC-BY-SA-3.0 requires attribution and share-alike:",
                "  adaptations must be shared under the same or a compatible",
                "  license.",
                "",
            ]
        if "CC-BY-NC-SA-4.0" in by_license:
            lines += [
                "  CC-BY-NC-SA-4.0 requires attribution, share-alike, and",
                "  prohibits commercial use. A distribution containing these",
                "  artifacts may not be used for commercial purposes.",
                "",
            ]

    lines += ["Per-artifact detail", "-" * 19, ""]
    for path, manifest in manifests:
        lines.append(f"[{manifest['artifact_id']}]  ({path.parent.relative_to(ROOT)})")
        for key in (
            "artifact_version",
            "upstream_name",
            "upstream_release",
            "upstream_url",
            "upstream_commit_or_doi",
            "retrieved",
            "license_spdx",
            "citation",
            "transformation",
            "redistribution_notes",
        ):
            value = manifest.get(key)
            lines.append(f"  {key + ':':<24} {value if value is not None else '(n/a)'}")
        for name, digest in manifest.get("input_sha256", {}).items():
            lines.append(f"  {'sha256(' + name + '):':<24} {digest}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def restamp() -> int:
    """Recompute input_sha256 after a deliberate data change.

    The hashes are what make a manifest a record of specific bytes rather than a
    label, so they are checked and must be refreshed explicitly.
    """
    count = 0
    for path, manifest in load_manifests():
        directory = path.parent
        manifest["input_sha256"] = {
            source.name: hashlib.sha256(source.read_bytes()).hexdigest()
            for source in sorted(directory.iterdir())
            if source.is_file() and source.name != "provenance.json"
        }
        path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        count += 1
    print(f"Re-stamped {count} provenance manifest(s).")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if NOTICE is out of date")
    parser.add_argument(
        "--restamp",
        action="store_true",
        help="recompute provenance input hashes after a deliberate data change",
    )
    args = parser.parse_args()

    if args.restamp:
        restamp()

    rendered = render()
    if args.check:
        current = NOTICE.read_text(encoding="utf-8") if NOTICE.exists() else ""
        if current != rendered:
            print("NOTICE is stale; run scripts/generate_notice.py", file=sys.stderr)
            return 1
        print("NOTICE is up to date.")
        return 0

    NOTICE.write_text(rendered, encoding="utf-8")
    print(f"Wrote {NOTICE.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
