const GUIDE_STEPS = [
  {
    "title": "What merkmal provides",
    "content": "<p>merkmal maps IPA graphemes to phonological features and computes distances between segments. Given a segment and a feature system, it returns that segment’s feature bundle. Given two segments, it returns a distance derived from their shared and differing features, weighted by the system’s geometry.</p><p>That is the scope. It does not align sequences, reconstruct proto-forms, or evaluate competing feature theories. Those are separate problems that use feature distances as an input, and conflating the distance computation with the things that consume it would make both harder to inspect.</p><p>Several feature systems are built in — PHOIBLE, BIPA/CLTS, P-base variants, and others — each with its own geometry and scoring. You can also register a custom model in the text format documented below.</p>"
  },
  {
    "title": "Looking up features",
    "content": "<p>The Features tab takes a single IPA grapheme and returns its feature bundle in the selected system.</p><p>Type a segment — a base character with any diacritics, or a multi-character grapheme like <code>pʰ</code> or <code>t͡ʃ</code> — and the output appears immediately. The feature set is the system’s answer to the question “what kind of sound is this?”: its manner, place, voicing, and whatever other dimensions the system models.</p><p>Categorical systems return a flat set of feature labels (<code>voiceless</code>, <code>bilabial</code>, <code>stop</code>). Metric systems also return a numeric feature vector: each label gets a value, and it is these values that the distance computation uses. A value of <code>+1</code> means the feature is present, <code>−1</code> means it is absent, and fractional values appear when a system encodes gradient contrasts.</p><p>If the grapheme is not in the system’s inventory, merkmal attempts to resolve it — stripping tie bars, retracting affricates, decomposing diacritics — and reports which resolution path succeeded. A grapheme that cannot be resolved at all is an error, which usually means it is not a sound the system was built to handle.</p>",
    "example": { "tab": "features", "inputs": { "feat-grapheme": "pʰ" } }
  },
  {
    "title": "Segment distances",
    "content": "<p>The Distance tab takes two segments and returns a number between 0 and 1. Zero means the system considers them identical; one means they share nothing.</p><p>The distance is not a simple Hamming count. Each system defines a geometry — a tree of feature nodes — and the distance weights each dimension by its depth in that tree. A difference in manner contributes more than a difference in secondary articulation, because the geometry says so, not because of a post-hoc choice.</p><p>Coverage reports what fraction of the two segments’ combined feature dimensions actually overlap. Two segments from different tiers — a consonant and a tone letter, say — share no dimensions, and the distance between them is undefined. Coverage below 100% means some features of one segment had no counterpart in the other; the reported distance is computed over the shared portion only.</p>",
    "example": { "tab": "distance", "inputs": { "dist-a": "p", "dist-b": "b" } }
  },
  {
    "title": "Tokenizing IPA strings",
    "content": "<p>The Tokenizer tab splits an IPA string into segments. This is not character splitting: <code>pʰ</code> is one segment, <code>t͡ʃ</code> is one segment, and a vowel carrying a combining diacritic is one segment. Splitting on characters would break every one of them.</p><p>Two options control the tokenizer’s behaviour:</p><p><strong>System-aware</strong> uses the selected feature system’s inventory to decide where segment boundaries fall. It greedily matches the longest prefix that the system recognises as a valid segment. With this off, segmentation relies only on Unicode categories — useful when you want to see what the string contains without committing to a system.</p><p><strong>Merge tones</strong> groups consecutive tone digits or tone letters into a single tone segment and attaches them to the preceding vowel or syllabic consonant. Chao notation (<code>¹²</code>, <code>˥˩</code>, or plain digits <code>0</code>–<code>5</code>) is recognised. With this off, each digit or tone letter stays as its own token.</p><p>Segments the system cannot recognise are highlighted. That is diagnostic information: it tells you what the system does not cover, which is worth knowing before computing distances over a dataset that contains those segments.</p>",
    "example": { "tab": "tokenizer", "inputs": { "tok-input": "tʰoŋ⁵⁵" } }
  },
  {
    "title": "Distance matrices",
    "content": "<p>The Matrix tab takes a list of segments — separated by spaces, commas, or both — and returns the pairwise distance matrix. This is the batch form of the Distance tab: each cell is the same geometry-weighted distance, and the matrix is symmetric with zeros on the diagonal.</p><p>A cell showing “—” means the distance is undefined for that pair, usually because the two segments share no feature dimensions.</p><p>The matrix is what you would feed into a clustering algorithm, a neighbour-joining tree, or a sequence alignment scorer. It is the raw material, not a conclusion.</p>",
    "example": { "tab": "matrix", "inputs": { "mat-input": "p b t d k g" } }
  },
  {
    "title": "Feature systems",
    "content": "<p>A feature system is a mapping from graphemes to feature bundles, plus a geometry that weights the dimensions. Different systems exist because phonological theory is not settled: which features are primitive, how many there are, and how they relate to each other are open questions with competing answers.</p><p>The built-in systems include:</p><ul><li><strong>BIPA / CLTS</strong> — the Broad IPA system from the Cross-Linguistic Transcription Systems project, with a categorical feature set.</li><li><strong>PHOIBLE</strong> — derived from the PHOIBLE database, which aggregates inventories from multiple sources.</li><li><strong>P-base</strong> — derived from P-base, in several geometric variants.</li></ul><p>The system selector shows each system’s type: <em>categorical</em> systems assign binary feature bundles, while <em>metric</em> systems produce numeric vectors. The distance computation handles both, but the underlying arithmetic differs: categorical distances are set-theoretic, metric distances are geometric.</p><p>Which system is appropriate depends on your research question. merkmal does not make that choice; it computes what the selected system says.</p>"
  },
  {
    "title": "Custom models",
    "content": "<p>The “Register a custom model” panel accepts a model in merkmal’s text format. A model defines a name, a type, a geometry, the feature dimensions, and the grapheme–feature mappings:</p><pre><code>@model custom\n@type categorical\n@geometry clements-hume\nfeature consonant major\ngrapheme p consonant voiceless bilabial stop\ngrapheme b consonant voiced bilabial stop</code></pre><p>Lines beginning with <code>@model</code> name the system. <code>@type</code> is either <code>categorical</code> or <code>metric</code>. <code>@geometry</code> names the distance geometry (the built-in options appear in the source). Each <code>feature</code> line declares a dimension and its position in the geometry tree. Each <code>grapheme</code> line maps a segment to its feature bundle.</p><p>Once registered, the custom system appears in the system selector alongside the built-in ones. It is available for the rest of the session; refreshing the page discards it.</p><p>This is useful for testing a feature analysis before committing it to a model file, or for working with a small inventory that the built-in systems do not cover.</p>"
  }
];
